env:
  global:
    - secure: VXI49IEmNxeJ799LCHItlclQ9fD2Wkqtl2NyTk3ynwJajrxJtsUwZa1NAgvJJ9sftwnTCB77Chto7pOn6xacK3do/W0fNweW8aAeqVeyGexFt3N3DGhdt52oznvk7ECTdvB1du5msQQQgwb4M2aNQ6ZIycrsaGYIJHWyJTuLxvI=
language: rust
script:
  - cargo build --verbose
  - cargo test --verbose
  - rustdoc --test README.md -L target
  - cargo doc --verbose
notifications:
  email: false
  irc:
    channels:
      - "irc.fyrechat.net#vana-commits"
    template:
      - "%{repository_slug}/%{branch} (%{commit} - %{author}): %{message}"
    skip_join: true
after_script:
  - cp -r target/doc doc
  - curl http://www.rust-ci.org/artifacts/put?t=$RUSTCI_TOKEN | sh
